version: '3.8'

services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    networks:
      - monitoring
    environment:
      - PROMETHEUS_CONFIG=/etc/prometheus/prometheus.yml

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - prometheus
      - loki

  loki:
    # build:
    #   context: ./loki
    #   dockerfile: Dockerfile
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    networks:
      - monitoring
    environment:
      - LOKI_CONFIG=/etc/loki/loki-config.yaml

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    container_name: keycloak
    ports:
      - "8081:8081"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  loki_data:
  keycloak_data:
