global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'back-node_exporter'
    static_configs:
      - targets: ['backend:9100']
  
  - job_name: 'front-node_exporter'
    static_configs:
      - targets: ['frontend:9100']
  
  - job_name: 'host-windows_exporter'
    static_configs:
      - targets: ['host.docker.internal:9182']