apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: "http://prometheus:9090"
    jsonData:
      sslmode: "disable"
    is_default: true
    editable: true
    version: 1

  - name: Loki
    type: loki
    access: proxy
    url: "http://loki:3100"
    jsonData:
      sslmode: "disable"
    is_default: true
    editable: true
    version: 1    